const fs = require('fs');

const L = [];
const p = (s) => L.push(s);

p("let SUPABASE_URL = (process.env.SUPABASE_URL || '')");
p("  .replace(/\\/+$/, '').replace(/\\/rest\\/v1.*$/, '').replace(/\\/+$/, '');");
p("const SUPABASE_KEY = process.env.SUPABASE_KEY;");
p("const CONGRESS_KEY = process.env.CONGRESS_API_KEY;");
p("const headers = {");
p("  apikey: SUPABASE_KEY,");
p("  Authorization: 'Bearer ' + SUPABASE_KEY,");
p("  'Content-Type': 'application/json',");
p("};");
p("function parseBillId(raw) {");
p("  if (!raw) return null;");
p("  const s = raw.replace(/\\./g, '').replace(/\\s+/g, ' ').trim().toUpperCase();");
p("  const m = s.match(/^([A-Z]+(?:\\s[A-Z]+)*)\\s(\\d+)$/);");
p("  if (!m) return null;");
p("  const typeMap = {");
p("    'H R': 'hr', 'HR': 'hr', 'S': 's',");
p("    'H RES': 'hres', 'HRES': 'hres',");
p("    'S RES': 'sres', 'SRES': 'sres',");
p("    'H J RES': 'hjres', 'HJRES': 'hjres',");
p("    'S J RES': 'sjres', 'SJRES': 'sjres',");
p("    'H CON RES': 'hconres', 'HCONRES': 'hconres',");
p("    'S CON RES': 'sconres', 'SCONRES': 'sconres'");
p("  };");
p("  const type = typeMap[m[1]];");
p("  return type ? { type: type, number: m[2] } : null;");
p("}");
p("(async () => {");
p("  console.log('\\n=== BACKFILL POLICY AREAS ===\\n');");
p("  const vRes = await fetch(SUPABASE_URL + '/rest/v1/votes?policy_area=is.null&select=id,chamber,roll_call,bill_id,congress', { headers: headers });");
p("  const votes = await vRes.json();");
p("  console.log('votes missing policy_area: ' + votes.length + '\\n');");
p("  const cache = {};");
p("  let updated = 0;");
p("  let skipped = 0;");
p("  for (const v of votes) {");
p("    const parsed = parseBillId(v.bill_id);");
p("    if (!parsed) { console.log('  ' + (v.bill_id || 'no bill') + ': cannot parse'); skipped++; continue; }");
p("    const key = v.congress + '/' + parsed.type + '/' + parsed.number;");
p("    let area = cache[key];");
p("    if (area === undefined) {");
p("      const url = 'https://api.congress.gov/v3/bill/' + v.congress + '/' + parsed.type + '/' + parsed.number + '?format=json&api_key=' + CONGRESS_KEY;");
p("      try {");
p("        const res = await fetch(url);");
p("        if (!res.ok) { console.log('  ' + v.bill_id + ': HTTP ' + res.status); cache[key] = null; skipped++; continue; }");
p("        const d = await res.json();");
p("        area = (d.bill && d.bill.policyArea) ? d.bill.policyArea.name : null;");
p("        cache[key] = area;");
p("      } catch (e) {");
p("        console.log('  ' + v.bill_id + ': ERROR ' + e.message);");
p("        skipped++; continue;");
p("      }");
p("    }");
p("    if (!area) { console.log('  ' + v.bill_id + ': no policy area listed'); skipped++; continue; }");
p("    const upd = await fetch(SUPABASE_URL + '/rest/v1/votes?id=eq.' + v.id, {");
p("      method: 'PATCH', headers: headers, body: JSON.stringify({ policy_area: area })");
p("    });");
p("    if (upd.ok) {");
p("      updated++;");
p("      console.log('  ' + String(v.bill_id).padEnd(16) + ' -> ' + area);");
p("    } else {");
p("      console.log('  ' + v.bill_id + ': update failed ' + upd.status);");
p("      skipped++;");
p("    }");
p("  }");
p("  console.log('\\nupdated ' + updated + ', skipped ' + skipped);");
p("  const allRes = await fetch(SUPABASE_URL + '/rest/v1/votes?select=policy_area', { headers: headers });");
p("  const all = await allRes.json();");
p("  const tally = {};");
p("  all.forEach(function (r) { const k = r.policy_area || '(none)'; tally[k] = (tally[k] || 0) + 1; });");
p("  console.log('\\n=== POLICY AREAS IN DATABASE ===');");
p("  Object.keys(tally).sort().forEach(function (k) { console.log('  ' + String(tally[k]).padStart(3) + '  ' + k); });");
p("  console.log('');");
p("})();");

fs.writeFileSync('backfill-policy-areas.js', L.join('\n'), 'utf8');
console.log('\nWrote backfill-policy-areas.js\n');