const fs = require('fs');

const L = [];
const p = (s) => L.push(s);

p("let SUPABASE_URL = (process.env.SUPABASE_URL || '')");
p("  .replace(/\\/+$/, '').replace(/\\/rest\\/v1.*$/, '').replace(/\\/+$/, '');");
p("const SUPABASE_KEY = process.env.SUPABASE_KEY;");
p("const CLAUDE_KEY = process.env.CLAUDE_KEY;");
p("const CONGRESS_KEY = process.env.CONGRESS_API_KEY;");
p("const MAX = parseInt(process.env.EXPLAIN_MAX || '5', 10);");
p("const headers = {");
p("  apikey: SUPABASE_KEY,");
p("  Authorization: 'Bearer ' + SUPABASE_KEY,");
p("  'Content-Type': 'application/json',");
p("};");
p("function parseBillId(raw) {");
p("  if (!raw) return null;");
p("  const s = raw.replace(/\\./g, '').replace(/\\s+/g, ' ').trim().toUpperCase();");
p("  const m = s.match(/^([A-Z]+(?:\\s[A-Z]+)*)\\s(\\d+)$/);");
p("  if (!m) return null;");
p("  const typeMap = { 'H R':'hr','HR':'hr','S':'s','H RES':'hres','HRES':'hres','S RES':'sres','SRES':'sres','H J RES':'hjres','HJRES':'hjres','S J RES':'sjres','SJRES':'sjres','H CON RES':'hconres','HCONRES':'hconres','S CON RES':'sconres','SCONRES':'sconres' };");
p("  const type = typeMap[m[1]];");
p("  return type ? { type: type, number: m[2] } : null;");
p("}");
p("(async () => {");
p("  console.log('\\n=== EXPLAIN VOTES (max ' + MAX + ') ===\\n');");
p("  const vRes = await fetch(SUPABASE_URL + '/rest/v1/votes?yes_means=is.null&is_final_passage=eq.true&select=id,bill_id,congress,question,description,policy_area,result&order=vote_date.desc&limit=' + MAX, { headers: headers });");
p("  const votes = await vRes.json();");
p("  console.log('votes needing explanation: ' + votes.length + '\\n');");
p("  let done = 0;");
p("  for (const v of votes) {");
p("    let billTitle = v.description || '';");
p("    let billSummary = '';");
p("    const parsed = parseBillId(v.bill_id);");
p("    if (parsed) {");
p("      try {");
p("        const bRes = await fetch('https://api.congress.gov/v3/bill/' + v.congress + '/' + parsed.type + '/' + parsed.number + '?format=json&api_key=' + CONGRESS_KEY);");
p("        if (bRes.ok) {");
p("          const bd = await bRes.json();");
p("          if (bd.bill && bd.bill.title) billTitle = bd.bill.title;");
p("        }");
p("        const sRes = await fetch('https://api.congress.gov/v3/bill/' + v.congress + '/' + parsed.type + '/' + parsed.number + '/summaries?format=json&api_key=' + CONGRESS_KEY);");
p("        if (sRes.ok) {");
p("          const sd = await sRes.json();");
p("          const list = sd.summaries || [];");
p("          if (list.length) billSummary = String(list[list.length - 1].text || '').replace(/<[^>]*>/g, ' ').replace(/\\s+/g, ' ').trim().substring(0, 2500);");
p("        }");
p("      } catch (e) { /* fall back to description */ }");
p("    }");
p("    const prompt = 'You are a strictly nonpartisan civic educator. Explain what this congressional vote means for ordinary people.\\n\\n' +");
p("      'Bill: ' + (v.bill_id || 'unknown') + '\\n' +");
p("      'Title: ' + billTitle + '\\n' +");
p("      'Vote question: ' + (v.question || '') + '\\n' +");
p("      'Policy area: ' + (v.policy_area || '') + '\\n' +");
p("      (billSummary ? 'Official summary: ' + billSummary + '\\n' : '') +");
p("      '\\nRules you must follow:\\n' +");
p("      '- Neutral throughout. Do not imply either vote is correct, responsible, or harmful.\\n' +");
p("      '- Describe consequences, not virtues. No praise or criticism of either position.\\n' +");
p("      '- Plain language, no jargon. Assume no political background.\\n' +");
p("      '- If effects are uncertain or disputed, say so rather than picking a side.\\n' +");
p("      '- Use parallel structure for yes_means and no_means so neither sounds better.\\n\\n' +");
p("      'Respond ONLY with JSON (no markdown):\\n' +");
p("      '{\\n' +");
p("      '  \"plain_summary\": \"One or two sentences: what this bill or resolution would do. Max 40 words.\",\\n' +");
p("      '  \"yes_means\": \"A yes vote means... Describe the concrete effect. Max 30 words.\",\\n' +");
p("      '  \"no_means\": \"A no vote means... Describe the concrete effect. Max 30 words.\",\\n' +");
p("      '  \"who_affected\": \"Who this touches most directly. Max 20 words.\"\\n' +");
p("      '}';");
p("    try {");
p("      const cRes = await fetch('https://api.anthropic.com/v1/messages', {");
p("        method: 'POST',");
p("        headers: { 'Content-Type': 'application/json', 'x-api-key': CLAUDE_KEY, 'anthropic-version': '2023-06-01' },");
p("        body: JSON.stringify({ model: 'claude-sonnet-4-6', max_tokens: 700, messages: [{ role: 'user', content: prompt }] })");
p("      });");
p("      if (!cRes.ok) { console.log('  ' + v.bill_id + ': Claude ' + cRes.status + ' ' + (await cRes.text()).substring(0, 120)); continue; }");
p("      const cd = await cRes.json();");
p("      let raw = (cd.content || []).map(function (c) { return c.type === 'text' ? c.text : ''; }).join('').trim();");
p("      raw = raw.replace(/```json|```/g, '').trim();");
p("      const first = raw.indexOf('{');");
p("      const last = raw.lastIndexOf('}');");
p("      if (first !== -1 && last > first) raw = raw.substring(first, last + 1);");
p("      const out = JSON.parse(raw);");
p("      const upd = await fetch(SUPABASE_URL + '/rest/v1/votes?id=eq.' + v.id, {");
p("        method: 'PATCH', headers: headers,");
p("        body: JSON.stringify({");
p("          plain_summary: out.plain_summary,");
p("          yes_means: out.yes_means,");
p("          no_means: out.no_means,");
p("          who_affected: out.who_affected,");
p("          explained_at: new Date().toISOString()");
p("        })");
p("      });");
p("      if (!upd.ok) { console.log('  ' + v.bill_id + ': save failed ' + upd.status); continue; }");
p("      done++;");
p("      console.log('--- ' + v.bill_id + ' (' + (v.policy_area || '') + ') ---');");
p("      console.log('  WHAT: ' + out.plain_summary);");
p("      console.log('  YES:  ' + out.yes_means);");
p("      console.log('  NO:   ' + out.no_means);");
p("      console.log('  WHO:  ' + out.who_affected);");
p("      console.log('');");
p("    } catch (e) {");
p("      console.log('  ' + v.bill_id + ': ERROR ' + e.message);");
p("    }");
p("  }");
p("  console.log('Done. ' + done + ' votes explained.\\n');");
p("})();");

fs.writeFileSync('explain-votes.js', L.join('\n'), 'utf8');
console.log('\nWrote explain-votes.js\n');