const fs = require('fs');

const L = [];
const p = (s) => L.push(s);

p("let SUPABASE_URL = (process.env.SUPABASE_URL || '')");
p("  .replace(/\\/+$/, '').replace(/\\/rest\\/v1.*$/, '').replace(/\\/+$/, '');");
p("const SUPABASE_KEY = process.env.SUPABASE_KEY;");
p("const YEAR = 2026;");
p("const CONGRESS = 119;");
p("const SESSION = 2;");
p("const MAX_VOTES = 15;");
p("const SCAN_LIMIT = 120;");
p("const headers = {");
p("  apikey: SUPABASE_KEY,");
p("  Authorization: 'Bearer ' + SUPABASE_KEY,");
p("  'Content-Type': 'application/json',");
p("  Prefer: 'resolution=merge-duplicates',");
p("};");
p("function tag(xml, name) {");
p("  const re = new RegExp('<' + name + '>([\\\\s\\\\S]*?)<\\\\/' + name + '>');");
p("  const m = xml.match(re);");
p("  return m ? m[1].trim() : '';");
p("}");
p("function isFinalPassage(q, type) {");
p("  const s = ((q || '') + ' ' + (type || '')).toLowerCase();");
p("  if (/quorum|journal|adjourn|motion to table|previous question|amendment|recommit|order of business/.test(s)) return false;");
p("  return /on passage|on motion to suspend the rules and pass|on concurring|on agreeing to the resolution|conference report/.test(s);");
p("}");
p("(async () => {");
p("  console.log('\\n=== HOUSE VOTE INGEST ===\\n');");
p("  const existRes = await fetch(SUPABASE_URL + '/rest/v1/votes?chamber=eq.House&congress=eq.' + CONGRESS + '&select=roll_call', { headers: headers });");
p("  const existing = new Set((await existRes.json()).map(function (r) { return Number(r.roll_call); }));");
p("  console.log('already stored: ' + existing.size);");
p("  const memRes = await fetch(SUPABASE_URL + '/rest/v1/members?chamber=eq.House&select=bioguide_id', { headers: headers });");
p("  const known = new Set((await memRes.json()).map(function (m) { return m.bioguide_id; }));");
p("  console.log('house members indexed: ' + known.size + '\\n');");
p("  let saved = 0;");
p("  let scanned = 0;");
p("  for (let roll = SCAN_LIMIT; roll >= 1 && saved < MAX_VOTES; roll--) {");
p("    if (existing.has(roll)) continue;");
p("    const padded = String(roll).padStart(3, '0');");
p("    const url = 'https://clerk.house.gov/evs/' + YEAR + '/roll' + padded + '.xml';");
p("    try {");
p("      const res = await fetch(url, { headers: { 'User-Agent': 'CivicLens/1.0' } });");
p("      if (!res.ok) continue;");
p("      const xml = await res.text();");
p("      scanned++;");
p("      const question = tag(xml, 'vote-question');");
p("      const voteType = tag(xml, 'vote-type');");
p("      if (!isFinalPassage(question, voteType)) continue;");
p("      const legisNum = tag(xml, 'legis-num');");
p("      const rawDate = tag(xml, 'action-date');");
p("      const parsedDate = new Date(rawDate);");
p("      const voteDate = isNaN(parsedDate) ? null : parsedDate.toISOString().split('T')[0];");
p("      const recRe = new RegExp('<recorded-vote>([\\\\s\\\\S]*?)<\\\\/recorded-vote>', 'g');");
p("      const positions = [];");
p("      let m;");
p("      while ((m = recRe.exec(xml)) !== null) {");
p("        const block = m[1];");
p("        const idRe = new RegExp('name-id=\"([^\"]+)\"');");
p("        const idMatch = block.match(idRe);");
p("        const bio = idMatch ? idMatch[1] : null;");
p("        const cast = tag(block, 'vote');");
p("        if (bio) positions.push({ bioguide_id: bio, position: cast });");
p("      }");
p("      if (!positions.length) continue;");
p("      const count = function (t) { return positions.filter(function (x) { return x.position === t; }).length; };");
p("      const voteRow = {");
p("        chamber: 'House', congress: CONGRESS, session: SESSION, roll_call: roll,");
p("        vote_date: voteDate, bill_id: legisNum || null,");
p("        question: question,");
p("        description: tag(xml, 'vote-desc').substring(0, 500),");
p("        result: tag(xml, 'vote-result'),");
p("        policy_area: null, is_final_passage: true,");
p("        yea_count: count('Yea') + count('Aye'),");
p("        nay_count: count('Nay') + count('No'),");
p("        present_count: count('Present'),");
p("        not_voting_count: count('Not Voting'),");
p("      };");
p("      const insHeaders = Object.assign({}, headers, { Prefer: 'return=representation' });");
p("      const ins = await fetch(SUPABASE_URL + '/rest/v1/votes', { method: 'POST', headers: insHeaders, body: JSON.stringify(voteRow) });");
p("      if (!ins.ok) { console.log('roll ' + roll + ': save failed ' + ins.status + ' ' + (await ins.text()).substring(0, 150)); continue; }");
p("      const inserted = (await ins.json())[0];");
p("      console.log('roll ' + roll + ': ' + (legisNum || 'no bill') + ' (' + voteRow.yea_count + '-' + voteRow.nay_count + ')');");
p("      saved++;");
p("      const mvRows = [];");
p("      let unmatched = 0;");
p("      for (const pos of positions) {");
p("        if (!known.has(pos.bioguide_id)) { unmatched++; continue; }");
p("        mvRows.push({ vote_id: inserted.id, bioguide_id: pos.bioguide_id, position: pos.position });");
p("      }");
p("      if (mvRows.length) {");
p("        const mvRes = await fetch(SUPABASE_URL + '/rest/v1/member_votes', { method: 'POST', headers: headers, body: JSON.stringify(mvRows) });");
p("        console.log('   ' + mvRows.length + ' member votes' + (unmatched ? ' (' + unmatched + ' unmatched)' : '') + (mvRes.ok ? '' : ' - SAVE FAILED ' + mvRes.status));");
p("      }");
p("    } catch (e) {");
p("      console.log('roll ' + roll + ': ERROR ' + e.message);");
p("    }");
p("  }");
p("  console.log('\\nDone. scanned ' + scanned + ' roll calls, ingested ' + saved + '.\\n');");
p("})();");

fs.writeFileSync('ingest-house-votes.js', L.join('\n'), 'utf8');
console.log('\nWrote ingest-house-votes.js\n');