const fs = require('fs');

const L = [];
const p = (s) => L.push(s);

p("let SUPABASE_URL = (process.env.SUPABASE_URL || '')");
p("  .replace(/\\/+$/, '').replace(/\\/rest\\/v1.*$/, '').replace(/\\/+$/, '');");
p("const SUPABASE_KEY = process.env.SUPABASE_KEY;");
p("const CONGRESS = 119;");
p("const SESSION = 2;");
p("const MAX_VOTES = 15;");
p("const headers = {");
p("  apikey: SUPABASE_KEY,");
p("  Authorization: 'Bearer ' + SUPABASE_KEY,");
p("  'Content-Type': 'application/json',");
p("  Prefer: 'resolution=merge-duplicates',");
p("};");
p("function tag(xml, name) {");
p("  const re = new RegExp('<' + name + '>([\\\\s\\\\S]*?)<\\\\/' + name + '>');");
p("  const m = xml.match(re);");
p("  return m ? m[1].trim() : '';");
p("}");
p("function isFinalPassage(q) {");
p("  q = (q || '').toLowerCase();");
p("  if (/cloture|nomination|motion to proceed|motion to table|adjourn|quorum|amendment/.test(q)) return false;");
p("  return /on passage|on the bill|on the joint resolution|on the concurrent resolution|on the resolution|on the conference report/.test(q);");
p("}");
p("(async () => {");
p("  console.log('\\n=== SENATE VOTE INGEST ===\\n');");
p("  const menuUrl = 'https://www.senate.gov/legislative/LIS/roll_call_lists/vote_menu_' + CONGRESS + '_' + SESSION + '.xml';");
p("  const menuRes = await fetch(menuUrl, { headers: { 'User-Agent': 'CivicLens/1.0' } });");
p("  if (!menuRes.ok) { console.log('menu fetch failed: ' + menuRes.status); return; }");
p("  const menuXml = await menuRes.text();");
p("  const blocks = menuXml.split('<vote>').slice(1);");
p("  console.log('roll calls this session: ' + blocks.length);");
p("  const candidates = blocks");
p("    .map(function (b) { return { number: tag(b, 'vote_number'), question: tag(b, 'question') }; })");
p("    .filter(function (v) { return v.number && isFinalPassage(v.question); });");
p("  console.log('final passage votes: ' + candidates.length);");
p("  const existRes = await fetch(SUPABASE_URL + '/rest/v1/votes?chamber=eq.Senate&congress=eq.' + CONGRESS + '&session=eq.' + SESSION + '&select=roll_call', { headers: headers });");
p("  const existing = new Set((await existRes.json()).map(function (r) { return String(r.roll_call); }));");
p("  const todo = candidates.filter(function (v) { return !existing.has(String(parseInt(v.number, 10))); });");
p("  console.log('already stored: ' + existing.size + ' | to ingest: ' + todo.length + '\\n');");
p("  const memRes = await fetch(SUPABASE_URL + '/rest/v1/members?chamber=eq.Senate&select=bioguide_id,last_name,state', { headers: headers });");
p("  const senators = await memRes.json();");
p("  const lookup = {};");
p("  senators.forEach(function (s) { lookup[(s.last_name || '').toLowerCase() + '|' + (s.state || '').toUpperCase()] = s.bioguide_id; });");
p("  let saved = 0;");
p("  for (const v of todo.slice(0, MAX_VOTES)) {");
p("    const rollNum = parseInt(v.number, 10);");
p("    const padded = String(rollNum).padStart(5, '0');");
p("    const url = 'https://www.senate.gov/legislative/LIS/roll_call_votes/vote' + CONGRESS + SESSION + '/vote_' + CONGRESS + '_' + SESSION + '_' + padded + '.xml';");
p("    try {");
p("      const res = await fetch(url, { headers: { 'User-Agent': 'CivicLens/1.0' } });");
p("      if (!res.ok) { console.log('roll ' + rollNum + ': fetch ' + res.status); continue; }");
p("      const xml = await res.text();");
p("      const docRe = new RegExp('<document>([\\\\s\\\\S]*?)<\\\\/document>');");
p("      const doc = xml.match(docRe);");
p("      const docBlock = doc ? doc[1] : '';");
p("      const billId = tag(docBlock, 'document_name') || null;");
p("      const rawDate = tag(xml, 'vote_date');");
p("      const cleaned = rawDate.replace(/,\\s*\\d{2}:\\d{2}\\s*[AP]M/, '');");
p("      const parsedDate = new Date(cleaned);");
p("      const voteDate = isNaN(parsedDate) ? null : parsedDate.toISOString().split('T')[0];");
p("      const memberBlocks = xml.split('<member>').slice(1);");
p("      const positions = memberBlocks.map(function (mb) {");
p("        return { last_name: tag(mb, 'last_name'), state: tag(mb, 'state'), vote_cast: tag(mb, 'vote_cast') };");
p("      });");
p("      const count = function (t) { return positions.filter(function (x) { return x.vote_cast === t; }).length; };");
p("      const voteRow = {");
p("        chamber: 'Senate', congress: CONGRESS, session: SESSION, roll_call: rollNum,");
p("        vote_date: voteDate, bill_id: billId,");
p("        question: tag(xml, 'question'),");
p("        description: tag(xml, 'vote_document_text').substring(0, 500),");
p("        result: tag(xml, 'vote_result'),");
p("        policy_area: null, is_final_passage: true,");
p("        yea_count: count('Yea'), nay_count: count('Nay'),");
p("        present_count: count('Present'), not_voting_count: count('Not Voting'),");
p("      };");
p("      const insHeaders = Object.assign({}, headers, { Prefer: 'return=representation' });");
p("      const ins = await fetch(SUPABASE_URL + '/rest/v1/votes', { method: 'POST', headers: insHeaders, body: JSON.stringify(voteRow) });");
p("      if (!ins.ok) { console.log('roll ' + rollNum + ': save failed ' + ins.status + ' ' + (await ins.text()).substring(0, 150)); continue; }");
p("      const inserted = (await ins.json())[0];");
p("      console.log('roll ' + rollNum + ': ' + (billId || 'no bill') + ' (' + voteRow.yea_count + '-' + voteRow.nay_count + ')');");
p("      saved++;");
p("      const mvRows = [];");
p("      let unmatched = 0;");
p("      for (const pos of positions) {");
p("        const bio = lookup[(pos.last_name || '').toLowerCase() + '|' + (pos.state || '').toUpperCase()];");
p("        if (!bio) { unmatched++; continue; }");
p("        mvRows.push({ vote_id: inserted.id, bioguide_id: bio, position: pos.vote_cast });");
p("      }");
p("      if (mvRows.length) {");
p("        const mvRes = await fetch(SUPABASE_URL + '/rest/v1/member_votes', { method: 'POST', headers: headers, body: JSON.stringify(mvRows) });");
p("        console.log('   ' + mvRows.length + ' member votes' + (unmatched ? ' (' + unmatched + ' unmatched)' : '') + (mvRes.ok ? '' : ' - SAVE FAILED ' + mvRes.status));");
p("      }");
p("    } catch (e) {");
p("      console.log('roll ' + rollNum + ': ERROR ' + e.message);");
p("    }");
p("  }");
p("  console.log('\\nDone. ' + saved + ' votes ingested this run.\\n');");
p("})();");

fs.writeFileSync('ingest-senate-votes.js', L.join('\n'), 'utf8');
console.log('\nWrote ingest-senate-votes.js (' + L.length + ' lines)\n');